export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
}
import { ToastContainer } from "react-toastify";
import { Inter } from "next/font/google"
import "react-toastify/dist/ReactToastify.css"

const inter = Inter({ subsets: ["latin"] })
import "./globals.css"

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastContainer
          position="top-center"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="dark"
        />
        {children}
      </body>
    </html>
  )
}
